# Generated by Django 6.0.3 on 2026-04-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("poi_credit", "Mua lượt tạo POI"),
                    ("general", "Thanh toán khác"),
                ],
                default="general",
                help_text="Loại hóa đơn",
                max_length=20,
            ),
        ),
    ]
