# Generated by Django 6.0.3 on 2026-05-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_invoice_invoice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("poi_credit", "Mua lượt tạo POI"),
                    ("start_tour", "Thanh toán lượt tạo tour"),
                    ("buy_activation_code", "Partner mua code activation code"),
                    ("general", "Thanh toán khác"),
                ],
                default="general",
                help_text="Loại hóa đơn",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reference_id",
            field=models.CharField(
                help_text="Mã tham chiếu (ex: tourId)", max_length=100, null=True
            ),
        ),
    ]
