# Generated by Django 6.0.3 on 2026-05-01 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_invoice_invoice_type"),
        ("tours", "0004_tour_partner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="reference_id",
            field=models.CharField(
                help_text="Mã tham chiếu (tourId)", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("poi_credit", "Mua lượt tạo POI"),
                    ("start_tour", "Thanh toán lượt tạo tour"),
                    ("general", "Thanh toán khác"),
                ],
                default="general",
                help_text="Loại hóa đơn",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserAvailableTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expired_at", models.DateTimeField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_users",
                        to="tours.tour",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_tours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tour")},
            },
        ),
    ]
