# Generated by Django 6.0.3 on 2026-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_invoice_reference_id_alter_invoice_invoice_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paypal_event_id",
                    models.CharField(
                        db_index=True,
                        help_text="PayPal's own event UUID – used for idempotency",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g. PAYMENT.CAPTURE.COMPLETED", max_length=100
                    ),
                ),
                ("payload", models.JSONField(help_text="Raw JSON body from PayPal")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="payments_we_status_f91a85_idx",
                    )
                ],
            },
        ),
    ]
