# Generated by Django 6.0.3 on 2026-04-15 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pois", "0003_poi_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRevenueStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "batch_daily_revenue_stat",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BatchJob",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        choices=[
                            ("aggregate_daily_visits", "Aggregate Daily Visits"),
                            ("aggregate_daily_revenue", "Aggregate Daily Revenue"),
                            ("cleanup_old_history", "Cleanup Old History"),
                            ("sync_poi_status", "Sync POI Status"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="scheduler",
                        help_text="'scheduler', 'celery', or a user id / username",
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="Arbitrary dict with job-specific metrics",
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "batch_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_name", "status"],
                        name="batch_job_job_nam_a38e49_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="batch_job_created_6b2f4e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyVisitStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("visits", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_visit_stats",
                        to="pois.poi",
                    ),
                ),
            ],
            options={
                "db_table": "batch_daily_visit_stat",
                "indexes": [
                    models.Index(fields=["date"], name="batch_daily_date_936be9_idx")
                ],
                "unique_together": {("date", "poi")},
            },
        ),
    ]
