# Generated by Django 6.0.3 on 2026-04-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="poi_credits",
            field=models.IntegerField(default=0),
        ),
    ]
