# Generated by Django 6.0.3 on 2026-04-14 01:14

import django.db.models.deletion
import tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_tour_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourActivationCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        default=tours.models.generate_code, max_length=12, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tour",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_code",
                        to="tours.tour",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="tours_toura_code_2fd939_idx"),
                    models.Index(
                        fields=["expired_at"], name="tours_toura_expired_d32b45_idx"
                    ),
                ],
            },
        ),
    ]
