# Generated by Django 6.0.3 on 2026-05-09 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_tour_partner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="touractivationcode",
            name="days_credit",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="touractivationcode",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="touractivationcode",
            name="usage_limit",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="touractivationcode",
            name="used_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="touractivationcode",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activation_codes",
                to="tours.tour",
            ),
        ),
        migrations.CreateModel(
            name="TourActivationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("raw_code", models.CharField(max_length=12)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Thời điểm hết hạn của UserAvailableTour sau khi redeem",
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device_id"], name="tours_toura_device__2702a9_idx"
                    ),
                    models.Index(
                        fields=["raw_code"], name="tours_toura_raw_cod_7f2555_idx"
                    ),
                    models.Index(
                        fields=["activated_at"], name="tours_toura_activat_5e96f2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_id", "raw_code"),
                        name="unique_device_activation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAvailableTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                ("expired_at", models.DateTimeField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_users",
                        to="tours.tour",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_tours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("user__isnull", False),
                            ("device_id__isnull", False),
                            _connector="OR",
                        ),
                        name="require_user_or_device",
                    )
                ],
            },
        ),
    ]
