# Generated by Django 6.0.3 on 2026-04-09 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
        ("pois", "0002_alter_poi_type_audiopermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="poi_id",
        ),
        migrations.AddField(
            model_name="history",
            name="poi",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="pois.poi",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="history",
            constraint=models.UniqueConstraint(
                fields=("user", "poi"), name="unique_user_poi"
            ),
        ),
    ]
