# Generated by Django 6.0.3 on 2026-04-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0003_history_device_id_alter_history_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="tour_id",
            field=models.UUIDField(null=True),
        ),
    ]
