# Generated by Django 6.0.3 on 2026-04-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0004_history_tour_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="history",
            name="unique_user_poi",
        ),
    ]
