# Generated by Django 6.0.3 on 2026-04-03 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poi",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("default_lang", models.CharField(default="vi", max_length=10)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("drink", "Drink"),
                            ("museum", "Museum"),
                            ("park", "Park"),
                            ("historical", "Historical"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("radius", models.IntegerField(default=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="pois_poi_latitud_c9782c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LocalizedData",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lang_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("audio", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localized_data",
                        to="pois.poi",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("poi", "lang_code"), name="unique_poi_lang"
                    )
                ],
            },
        ),
    ]
