# Generated by Django 6.0.3 on 2026-04-09 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pois", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="poi",
            name="type",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("drink", "Drink"),
                    ("museum", "Museum"),
                    ("park", "Park"),
                    ("historical", "Historical"),
                    ("shopping", "Shopping"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AudioPermission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("poi_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "AudioPermission",
                "indexes": [
                    models.Index(
                        fields=["user", "poi_id"], name="AudioPermis_user_id_b6bc74_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "poi_id"), name="unique_user_poi_permission"
                    )
                ],
            },
        ),
    ]
