# Generated by Django 6.0.3 on 2026-05-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pois", "0003_poi_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="poi",
            name="h3_index",
            field=models.CharField(db_index=True, default="1234567890", max_length=16),
        ),
    ]
